### PR TITLE
Removed unused files

### PR DESCRIPTION
**Pull request by akmorrow13**
Removed unused testfiles, metastore_db, and empty README

### CODE REVIEW

**Review by heuermh — APPROVED** [review]

**Comment by heuermh** [comment]
Jenkins, add to whitelist

**Comment by heuermh** [comment]
Jenkins, test this please

**Comment by heuermh** [comment]
@fnothaft I guess I don't have the authority to kick Jenkins.  Is that a github project or organization setting, or something on Jenkins itself?  In any case, I was looking at the bdgenomics organization people and teams, and we should probably give those a refresh when I'm in town tomorrow or Friday.

**Comment by akmorrow13** [comment]
@tkdagdelen @devin-petersohn please approve

**Comment by akmorrow13** [comment]
Jenkins, test this please.

**Comment by akmorrow13** [comment]
@heuermh I added you as a collaborator. This should hopefully help.

**Pull request merged**
